#!/usr/bin/env bash
# Script that displays information about subdomains.

if [ $# -eq 1 ]; then
	dig +noall +answer 'www.'"$1" | awk '{ print "The subdomain www is a "$4" record and points to "$NF }'
	dig +noall +answer 'lb-01.'"$1" | awk '{ print "The subdomain lb-01 is a "$4" record and points to "$NF }'
	dig +noall +answer 'web-01.'"$1" | awk '{ print "The subdomain web-01 is a "$4" record and points to "$NF }'
	dig +noall +answer 'web-02.'"$1" | awk '{ print "The subdomain web-02 is a "$4" record and points to "$NF }'
elif [ $# -eq 2 ]; then
	dig +noall +answer "$2"'.'"$1" | awk -v a="$2" '{ print "The subdomain "a" is a "$4" record and points to "$NF }'
fi
