#!/usr/bin/env bash

# Update package index
apt-get update

# Install nginx
apt-get install -y nginx

# Overwrite the default index.html with Hello World!
echo 'Hello World!' > /var/www/html/index.html

# Restart nginx (no systemctl)
service nginx restart
