#!/usr/bin/env bash
# Configures a new ubuntu machine by installing
# Nginx where it should be listening on port 80
# Serve a page that would return a Hello World string
sudo apt-get  update
sudo apt-get install -y nginx

# allowing nginx on firewall
#ufw allow 'Nginx HTTP'

# Creating new index
echo 'Hello World!' > /var/www/html/index.html

# Starting nginx
service nginx restart

