#!/usr/bin/env bash
# Install nginx and configure it to serve "Hello World!" at /

set -e

# Install nginx
apt-get update -y
apt-get install -y nginx

# Ensure nginx is started
service nginx start || service nginx restart

# Replace default index.html content with Hello World!
echo 'Hello World!' > /var/www/html/index.html
