#!/usr/bin/env bash
#Configure a new Nginx server so that /redirect_me is redirecting to another page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

# Update nginx conf to add the redirect
sed -i '/server_name _;/a \
    location /redirect_me { \
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; \
    }' /etc/nginx/sites-available/default

sudo service nginx restart

