#!/usr/bin/env bash
#Configure web-02 to be identical to web-01
#Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)

sudo apt-get update
sudo apt-get install nginx -y

# Add custom header (insert in the server block of the default config)
sed -i '/server_name _;/a \
    add_header X-Served-By $hostname;' /etc/nginx/sites-available/default


# restart the web server after updating the settings
sudo service nginx restart
